name: Build Vue
on: [push]
jobs:
  pages:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'lelimacon'
        reponame: 'MemoryMachine'
        token: ${{ secrets.GITHUB_TOKEN }}
