name: Build Vue
on: [push]
jobs:
  pages:
    runs-on: ubuntu-latest
    name: pages
    steps:
    - uses: actions/checkout@v2
    - id: VuePages
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'lelimacon'
        reponame: 'MemoryMachine'
        token: ${{ secrets.GITHUB_TOKEN }}
